### ISSUE TITLE
Make the balance reports configurable

### ISSUE THREAD

**Issue by edgarrmondragon** [MeltanoLabs/tap-intacct#23]
The `trial_balances` and `account_balances` streams are currently retrieved by date range but more options are supported.

We might wanna enable users to customize the reports, e.g.

```yaml
plugins:
  extractors:
  - name: tap-intacct
    config:
      stream_options:
        trial_balances:
          # https://developer.intacct.com/api/general-ledger/trial-balances/
          reportingperiodname: Calendar Year Ended December 2022
          showlocdetail: true
        account_balances:
          # https://developer.intacct.com/api/general-ledger/account-balances/#list-account-balances-legacy
          reportingperiodname: Calendar Year Ended December 2022
          userDefinedDimensions:
          - objectName: category
            recordName: CAT1
```
